# Generated by Django 3.2.6 on 2021-08-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the project', max_length=50)),
                ('Description', models.TextField(help_text='Enter the description', max_length=1000)),
                ('back_end_technology', models.CharField(max_length=50, verbose_name='Backend Technology')),
                ('front_end_technology', models.CharField(max_length=50, verbose_name='Frontend Technology')),
            ],
        ),
    ]
